### ISSUE TITLE
Question about Num Bits

### ISSUE THREAD

**Issue by gauenk** [duanzhiihao/qres-vae#3]
I have see the bits-per pixel metric many times, but I find you code very easy to read. This motives me to ask this question.

On line 24 of the evaluation script is the line:

```
num_bits = tmp_bit_path.stat().st_size

```

Would you elaborating on how this evaluation works or point me to a reference? Perhaps the model's compression produces a variable length sequence, and the reference line above merely reports the output file size?

Thank you in advance :D

**Comment by duanzhiihao** [comment]
Thank you for your interest! I'm very happy to know that my code is readable :)

> Perhaps the model's compression produces a variable length sequence, and the reference line above merely reports the output file size? 

Exactly. `num_bits` is the file size (in bits) of the file at `tmp_bit_path`. For reference, please see https://stackoverflow.com/a/6591957 or https://docs.python.org/3/library/pathlib.html#pathlib.Path.stat

`num_bits` is later divided by the original image's height x width to get bits per pixel.

**Comment by gauenk** [comment]
Thank you for getting back to me so quickly. This is very interesting. I only want to confirm the following with you about how this variable length file is achieved:

(i) Your model compression comes from the ["discrete_gaussian" variable](https://github.com/duanzhiihao/qres-vae/blob/af2efe62b45eea62cd8a5545a1af651714751652/models/qresvae.py#L131).

(ii) The Gaussian Conditional layer ([described here](https://github.com/InterDigitalInc/CompressAI/blob/63346e910c59cd9a77fba140652be7c1dd857246/compressai/entropy_models/entropy_models.py#L551)) is the layer which produces the variable length sequence. The full paper about that aspect is "Variational image compression with a scale hyperprior".

**Comment by gauenk** [comment]
Oh perfect. Thank you!
