### ISSUE TITLE
Compress inference issue 

### ISSUE THREAD

**Issue by jjeremy40** [duanzhiihao/qres-vae#6]
Hi !
I'm encoutering a other pb : 
I'm trying to compress an img  with the following code (which is based on your demo.ipynb code ) : 

```
from models.library import qres34m
model = qres34m()
model.load_state_dict(torch.load(trained_weights_path)['model'])
model.eval()
model.compress_mode()
model.to(device)
x = Image.open("original.png")
x = transforms.functional.to_tensor(x).to("cuda")
x = x.unsqueeze(0)

h, w = x.size(2), x.size(3)
p = 64  # maximum 6 strides of 2
new_h = (h + p - 1) // p * p
new_w = (w + p - 1) // p * p
padding_left = (new_w - w) // 2
padding_right = new_w - w - padding_left
padding_top = (new_h - h) // 2
padding_bottom = new_h - h - padding_top
x_padded = F.pad(
    x,
    (padding_left, padding_right, padding_top, padding_bottom),
    mode="constant",
    value=0,
)

start = time.time()
out_enc = model.compress(x_padded)
enc_time = time.time() - start
with open("img.bits", 'wb') as f : 
        pickle.dump(out_enc, file=f)
bpp = (Path("img.bits").stat().st_size * 8.0) / (x.size(0) * x.size(2) * x.size(3))
print(bpp)

with open("img.bits", 'rb') as f : 
        out_enc = pickle.load(file=f)
    
start = time.time()
out_dec = model.decompress(out_enc)
dec_time = time.time() - start

temp = transforms.functional.to_pil_image(out_dec[0])
temp.show()
```

But I get very strange results... : 
**bpp = 73.605 (which is way to big !!)**
and the reconstructed img looks like this : 
![1_bpp_73 605_psnr_5 37_msssim_0 976](https://user-images.githubusercontent.com/44731689/213190496-19262877-1052-470b-87de-50ece8b9f672.png)

Do you know what I'm doing wrong ?

**Comment by duanzhiihao** [comment]
It looks very weird. However your code looks fine.
Could you provide the original image you use so that I can run the code and reproduce your results?

**Comment by jjeremy40** [comment]
Here's the original image : 
![original](https://user-images.githubusercontent.com/44731689/213204238-722a4f8a-0ce6-45da-8ce0-3dd6cb2a5ac9.png)

Thanks a lot !

**Comment by duanzhiihao** [comment]
Two more clarifications:
- What is your `trained_weights_path`  (or which lambda you are using)?
- What is your device, cuda or CPU?

**Comment by jjeremy40** [comment]
-  your pre-trained weights  and my currently training weights (they've reached around 35 epochs each, but on validation they already get pretty decent PSNR values)
- My device is GPU

**Comment by duanzhiihao** [comment]
I tried `'checkpoints/qres34m/lmb128/last_ema.pt'`.
The bpp = 0.14748 and the reconstruction looks normal.

> your pre-trained weights and my currently training weights (they've reached around 35 epochs each for lambda=[4, 8, 16, 32, 64], but on validation they already get pretty decent PSNR values)

I'm still a bit confused. Which weights would produce bpp = 73.605, is it my pre-trained weights, or is it one of your custom weights?

**Comment by jjeremy40** [comment]
Pb solved !
It was again due to the mistake in the shift (3789 instead of 0.3789) and scale value of my datasets....... I work on multiple computers and some time I forget to update the code from one to the other...

So sorry for the inconvenience. And thank you very much for the help.

**Comment by duanzhiihao** [comment]
Totally understand and no problem.
It's great to know that the problem is solved!
